#!/usr/bin/env python3
"""Generate THIRD_PARTY.md and sbom.json (CycloneDX 1.5) for one Taimen component.

Run it with the component's own virtual environment so that transitive
dependencies are included (the data source is importlib.metadata of the
running interpreter, not pyproject.toml). Sync a runtime-only environment first,
otherwise development tools (pytest, ruff, ...) end up in the list:

    cd services/control-plane && uv sync --no-dev
    uv run --no-sync python ../../tools/generate_third_party.py --component control-plane
    uv run --no-sync python ../../tools/generate_third_party.py --component control-plane --check

Copyleft licences (LGPL/GPL/AGPL/MPL/EUPL/CDDL) are listed in a separate section
with a statement about dynamic linking, because that is what determines the
obligations. NOTICE files are never touched by this script.

If the existing notice file contains the marker line
``<!-- generated-dependencies -->`` everything above the marker is preserved
(hand-written attributions, e.g. vendored code) and only the part below it is
regenerated; ``--check`` compares only the generated part.
"""

from __future__ import annotations

import argparse
import importlib.metadata as md
import json
import sys
from pathlib import Path
from typing import Any

MARKER = "<!-- generated-dependencies -->"
DEFAULT_EXCLUDE_PREFIXES = ("control-plane", "iam-service", "taimen-", "platform-")
COPYLEFT_MARKERS = ("LGPL", "GPL", "AGPL", "MPL", "EUPL", "CDDL")


def license_of(dist: md.Distribution) -> str:
    """Licence of a distribution: License-Expression, then License, then classifier."""
    meta = dist.metadata
    for field in ("License-Expression", "License"):
        value = meta.get(field)
        if value and len(value) < 200 and "\n" not in value:
            return value.strip()
    for classifier in meta.get_all("Classifier") or []:
        if classifier.startswith("License :: "):
            return str(classifier.removeprefix("License :: OSI Approved :: ").removeprefix("License :: "))
    return "UNKNOWN"


def is_copyleft(license_name: str) -> bool:
    upper = license_name.upper()
    return any(marker in upper for marker in COPYLEFT_MARKERS)


def collect_components(exclude_prefixes: tuple[str, ...]) -> list[dict[str, Any]]:
    components: list[dict[str, Any]] = []
    seen: set[str] = set()
    for dist in md.distributions():
        name = dist.metadata["Name"]
        if not name or name.lower().startswith(exclude_prefixes):
            continue
        key = f"{name.lower()}@{dist.version}"
        if key in seen:
            continue
        seen.add(key)
        license_name = license_of(dist)
        components.append(
            {
                "type": "library",
                "name": name,
                "version": dist.version,
                "purl": f"pkg:pypi/{name.lower()}@{dist.version}",
                "licenses": [{"license": {"name": license_name}}],
                "properties": [{"name": "copyleft", "value": str(is_copyleft(license_name))}],
            }
        )
    components.sort(key=lambda c: str(c["name"]).lower())
    return components


def build_sbom(component: str, components: list[dict[str, Any]]) -> dict[str, Any]:
    """CycloneDX 1.5 without timestamps, so the file only changes when dependencies do."""
    return {
        "bomFormat": "CycloneDX",
        "specVersion": "1.5",
        "version": 1,
        "metadata": {
            "component": {"type": "application", "name": component},
            "authors": [{"name": "Taimen contributors"}],
        },
        "components": components,
    }


def build_notice(component: str, components: list[dict[str, Any]]) -> str:
    copyleft = [c for c in components if c["properties"][0]["value"] == "True"]
    lines = [
        MARKER,
        "",
        f"## Third-party Python dependencies of `{component}`",
        "",
        "Generated by `tools/generate_third_party.py` from the installed environment",
        "(`uv.lock`); do not edit below the marker by hand. The machine-readable list is",
        "`sbom.json` (CycloneDX 1.5). Licence names come from package metadata.",
        "",
        "### Components under copyleft licences",
        "",
    ]
    if copyleft:
        lines += [
            "The components below are used under the following conditions:",
            "",
            "- linking is dynamic: the library is imported as is, there is no static linking;",
            "- the library source is neither modified nor vendored into this repository",
            "  (it is installed as a standard package from PyPI at the version pinned in `uv.lock`);",
            "- interaction goes through this component's own adapters, which remain under",
            "  this component's licence;",
            "- the user keeps the ability to replace or rebuild the library.",
            "",
        ]
        for c in copyleft:
            lines.append(f"- {c['name']} {c['version']} — {c['licenses'][0]['license']['name']}")
    else:
        lines.append("None.")
    lines += ["", "### Other third-party components", ""]
    for c in components:
        if c["properties"][0]["value"] == "True":
            continue
        lines.append(f"- {c['name']} {c['version']} — {c['licenses'][0]['license']['name']}")
    lines.append("")
    return "\n".join(lines)


def split_preserved(existing: str) -> str:
    """Hand-written part of the notice file (everything above the marker), '' if none."""
    if MARKER not in existing:
        return ""
    head = existing.split(MARKER, 1)[0]
    if not head:
        return ""
    return head if head.endswith("\n") else head + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--component", required=True, help="component name for the SBOM metadata")
    parser.add_argument("--root", default=".", help="component root (where THIRD_PARTY.md and sbom.json live)")
    parser.add_argument("--notice-path", default="THIRD_PARTY.md", help="notice file relative to --root")
    parser.add_argument("--sbom-path", default="sbom.json", help="SBOM file relative to --root")
    parser.add_argument(
        "--exclude-prefix",
        action="append",
        default=None,
        help="distribution-name prefixes to skip as first-party (repeatable); "
        f"default: {', '.join(DEFAULT_EXCLUDE_PREFIXES)}",
    )
    parser.add_argument("--check", action="store_true", help="write nothing; exit 1 if files are stale")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    notice_path = root / args.notice_path
    sbom_path = root / args.sbom_path
    exclude = tuple(args.exclude_prefix) if args.exclude_prefix else DEFAULT_EXCLUDE_PREFIXES

    components = collect_components(exclude)
    sbom_text = json.dumps(build_sbom(args.component, components), ensure_ascii=False, indent=2) + "\n"
    existing = notice_path.read_text(encoding="utf-8") if notice_path.exists() else ""
    notice_text = split_preserved(existing) + build_notice(args.component, components)

    if args.check:
        stale = [
            path
            for path, expected in ((sbom_path, sbom_text), (notice_path, notice_text))
            if not path.exists() or path.read_text(encoding="utf-8") != expected
        ]
        if stale:
            print(
                f"{args.component}: stale {', '.join(p.name for p in stale)}; "
                f"run: uv run python tools/generate_third_party.py --component {args.component}"
            )
            return 1
        print(f"{args.component}: THIRD_PARTY.md and sbom.json are up to date ({len(components)} components).")
        return 0

    sbom_path.parent.mkdir(parents=True, exist_ok=True)
    notice_path.parent.mkdir(parents=True, exist_ok=True)
    sbom_path.write_text(sbom_text, encoding="utf-8")
    notice_path.write_text(notice_text, encoding="utf-8")
    copyleft_count = sum(1 for c in components if c["properties"][0]["value"] == "True")
    print(
        f"{args.component}: wrote {notice_path.name} and {sbom_path.name}: "
        f"{len(components)} components, {copyleft_count} copyleft."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
